"""Add is_active column to User

Revision ID: 180c039bd4ea
Revises: a92e235465cc
Create Date: 2025-08-23 14:12:32.741181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180c039bd4ea'
down_revision = 'a92e235465cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
