"""add user profile fields + aliases

Revision ID: 18cad5340df4
Revises: 651a709c5144
Create Date: 2025-09-08 11:57:24.528474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cad5340df4'
down_revision = '651a709c5144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('employee_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('manager_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('phone')
        batch_op.drop_column('manager_name')
        batch_op.drop_column('job_title')
        batch_op.drop_column('department')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
