"""Add profile fields to users and updated_at to appraisals

Revision ID: 1eeaa2675820
Revises: 18cad5340df4
Create Date: 2025-09-08 12:24:12.792504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eeaa2675820'
down_revision = '18cad5340df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('job_title',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('manager_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['employee_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('location',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('manager_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('job_title',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
