"""initial user + appraisal models

Revision ID: 2ee6236374bf
Revises: 842aeed3dbda
Create Date: 2025-08-25 02:06:06.909596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ee6236374bf'
down_revision = '842aeed3dbda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'MANAGER', 'HR', 'ADMIN', name='role_enum'), server_default='EMPLOYEE', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('appraisals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('employee_comment', sa.Text(), nullable=True),
    sa.Column('supervisor_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('hr_id', sa.Integer(), nullable=True),
    sa.Column('self_goals', sa.Text(), nullable=True),
    sa.Column('self_achievements', sa.Text(), nullable=True),
    sa.Column('self_training', sa.Text(), nullable=True),
    sa.Column('self_rating', sa.Integer(), nullable=True),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('manager_rating', sa.Integer(), nullable=True),
    sa.Column('hr_comments', sa.Text(), nullable=True),
    sa.Column('promotion_recommended', sa.Boolean(), nullable=True),
    sa.Column('new_title', sa.String(length=120), nullable=True),
    sa.Column('new_salary', sa.Float(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED_TO_MANAGER', 'MANAGER_SUBMITTED', 'HR_REVIEWED', 'APPROVED', 'REJECTED', name='review_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hr_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('input_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('DRAFT', 'SUBMITTED_TO_MANAGER', 'MANAGER_SUBMITTED', 'HR_REVIEWED', 'APPROVED', 'REJECTED', name='review_status_enum'), nullable=True),
    sa.Column('to_status', sa.Enum('DRAFT', 'SUBMITTED_TO_MANAGER', 'MANAGER_SUBMITTED', 'HR_REVIEWED', 'APPROVED', 'REJECTED', name='review_status_enum'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['performance_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('example_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ),
    sa.ForeignKeyConstraint(['criteria_id'], ['criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appraisal_id', sa.Integer(), nullable=False),
    sa.Column('teaching_percent', sa.Integer(), nullable=True),
    sa.Column('research_percent', sa.Integer(), nullable=True),
    sa.Column('other_percent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appraisal_id'], ['appraisals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workloads')
    op.drop_table('scores')
    op.drop_table('review_audits')
    op.drop_table('predictions')
    op.drop_table('performance_reviews')
    op.drop_table('appraisals')
    op.drop_table('users')
    op.drop_table('criteria')
    # ### end Alembic commands ###
