"""add performance review + audit tables

Revision ID: 535ef0409b72
Revises: 02b88463fc90
Create Date: 2025-08-21 11:27:28.484437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535ef0409b72'
down_revision = '02b88463fc90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('hr_id', sa.Integer(), nullable=True),
    sa.Column('self_goals', sa.Text(), nullable=True),
    sa.Column('self_achievements', sa.Text(), nullable=True),
    sa.Column('self_training', sa.Text(), nullable=True),
    sa.Column('self_rating', sa.Integer(), nullable=True),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('manager_rating', sa.Integer(), nullable=True),
    sa.Column('hr_comments', sa.Text(), nullable=True),
    sa.Column('promotion_recommended', sa.Boolean(), nullable=True),
    sa.Column('new_title', sa.String(length=120), nullable=True),
    sa.Column('new_salary', sa.Float(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED_TO_MANAGER', 'MANAGER_SUBMITTED', 'HR_REVIEWED', 'APPROVED', 'REJECTED', name='reviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['hr_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('DRAFT', 'SUBMITTED_TO_MANAGER', 'MANAGER_SUBMITTED', 'HR_REVIEWED', 'APPROVED', 'REJECTED', name='reviewstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('DRAFT', 'SUBMITTED_TO_MANAGER', 'MANAGER_SUBMITTED', 'HR_REVIEWED', 'APPROVED', 'REJECTED', name='reviewstatus'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['performance_review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_audit')
    op.drop_table('performance_review')
    # ### end Alembic commands ###
