"""appraisal: add status column and ReviewAudit

Revision ID: a23d3f6af547
Revises: f7b6622cd552
Create Date: 2025-08-30 10:10:23.386109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23d3f6af547'
down_revision = 'f7b6622cd552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED_TO_MANAGER', 'MANAGER_SUBMITTED', 'HR_REVIEWED', 'APPROVED', 'REJECTED', name='review_status_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appraisals', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
